// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using frutaaaaa.Data;

#nullable disable

namespace frutaaaaa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251231120948_AddMarqueAssignmentTable")]
    partial class AddMarqueAssignmentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DailyProgramDetail", b =>
                {
                    b.Property<int>("NumProg")
                        .HasColumnType("int");

                    b.Property<int>("codgrv")
                        .HasColumnType("int");

                    b.Property<int?>("DailyProgramId")
                        .HasColumnType("int");

                    b.Property<int>("Nbrcoli")
                        .HasColumnType("int");

                    b.Property<int>("Nbrpal")
                        .HasColumnType("int");

                    b.Property<int>("Valide")
                        .HasColumnType("int");

                    b.Property<string>("codtyp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NumProg", "codgrv");

                    b.HasIndex("DailyProgramId");

                    b.ToTable("DailyProgramDetails");
                });

            modelBuilder.Entity("Destination", b =>
                {
                    b.Property<int>("coddes")
                        .HasColumnType("int");

                    b.Property<string>("vildes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("destination", (string)null);
                });

            modelBuilder.Entity("GrpVar", b =>
                {
                    b.Property<int>("codgrv")
                        .HasColumnType("int");

                    b.Property<string>("nomgrv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("grpvar", (string)null);
                });

            modelBuilder.Entity("Partenaire", b =>
                {
                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ref")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("partenaire", (string)null);
                });

            modelBuilder.Entity("UserPagePermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id")
                        .HasColumnOrder(0);

                    b.Property<string>("PageName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("page_name")
                        .HasColumnOrder(1);

                    b.Property<bool>("Allowed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("allowed");

                    b.HasKey("UserId", "PageName");

                    b.ToTable("user_page_permissions");
                });

            modelBuilder.Entity("frutaaaaa.Models.Bdq", b =>
                {
                    b.Property<int>("numbdq")
                        .HasColumnType("int");

                    b.Property<int?>("numdos")
                        .HasColumnType("int");

                    b.ToTable("bdq", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.DailyProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Coddes")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dteprog")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Havday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumProg")
                        .HasColumnType("int");

                    b.Property<string>("PO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Refexp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyPrograms");
                });

            modelBuilder.Entity("frutaaaaa.Models.Defaut", b =>
                {
                    b.Property<short>("Coddef")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("coddef");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("Coddef"));

                    b.Property<string>("Famdef")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("famdef");

                    b.Property<string>("Intdef")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("intdef");

                    b.HasKey("Coddef");

                    b.ToTable("defaut", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.Dossier", b =>
                {
                    b.Property<int?>("coddes")
                        .HasColumnType("int");

                    b.Property<int>("numdos")
                        .HasColumnType("int");

                    b.ToTable("dossier", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.EcartD", b =>
                {
                    b.Property<int>("numpre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("numpre"));

                    b.Property<int>("codtype")
                        .HasColumnType("int");

                    b.Property<int>("nbrcai")
                        .HasColumnType("int");

                    b.Property<int>("numpal")
                        .HasColumnType("int");

                    b.Property<int>("numver")
                        .HasColumnType("int");

                    b.Property<int>("palnum")
                        .HasColumnType("int");

                    b.Property<decimal>("pdsfru")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("refver")
                        .HasColumnType("int");

                    b.Property<string>("typemb")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("numpre");

                    b.ToTable("ecart_d", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.EcartDirect", b =>
                {
                    b.Property<int>("Numpal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Numpal"));

                    b.Property<int?>("Codtype")
                        .HasColumnType("int");

                    b.Property<int?>("Codvar")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Dtepal")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Numbl")
                        .HasColumnType("int");

                    b.Property<int?>("Numvent")
                        .HasColumnType("INT");

                    b.Property<double?>("Pdsfru")
                        .HasColumnType("DOUBLE");

                    b.Property<double?>("Pdsvent")
                        .HasColumnType("DOUBLE");

                    b.Property<int?>("Refver")
                        .HasColumnType("int");

                    b.HasKey("Numpal");

                    b.HasIndex("Codtype");

                    b.ToTable("ecart_direct", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.EcartE", b =>
                {
                    b.Property<int>("numpal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("numpal"));

                    b.Property<int>("codtype")
                        .HasColumnType("int");

                    b.Property<int>("codvar")
                        .HasColumnType("int");

                    b.Property<DateTime>("dtepal")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("numvent")
                        .HasColumnType("INT");

                    b.Property<double>("pdsfru")
                        .HasColumnType("double");

                    b.Property<double>("pdspes")
                        .HasColumnType("double");

                    b.Property<double?>("pdsvent")
                        .HasColumnType("DOUBLE");

                    b.Property<int?>("refver")
                        .HasColumnType("int");

                    b.Property<double>("tarpal")
                        .HasColumnType("double");

                    b.HasKey("numpal");

                    b.ToTable("ecart_e", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.Entreprise", b =>
                {
                    b.Property<string>("refent")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("camp")
                        .HasColumnType("longtext");

                    b.Property<string>("cpent")
                        .HasColumnType("longtext");

                    b.Property<string>("domaine")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("dtDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("dtFin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("faxent")
                        .HasColumnType("longtext");

                    b.Property<string>("lier")
                        .HasColumnType("longtext");

                    b.Property<string>("logent")
                        .HasColumnType("longtext");

                    b.Property<string>("noment")
                        .HasColumnType("longtext");

                    b.Property<uint?>("numau")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("numde")
                        .HasColumnType("int unsigned");

                    b.Property<string>("payent")
                        .HasColumnType("longtext");

                    b.Property<double?>("pmoyOuv")
                        .HasColumnType("double");

                    b.Property<double?>("pmoyPerm")
                        .HasColumnType("double");

                    b.Property<short?>("refsta1")
                        .HasColumnType("smallint");

                    b.Property<short?>("refsta2")
                        .HasColumnType("smallint");

                    b.Property<string>("repent")
                        .HasColumnType("longtext");

                    b.Property<string>("rueent")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("tarpal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("telent")
                        .HasColumnType("longtext");

                    b.Property<string>("type")
                        .HasColumnType("longtext");

                    b.Property<string>("typsta")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("typtrs")
                        .HasColumnType("longtext");

                    b.Property<string>("vilent")
                        .HasColumnType("longtext");

                    b.HasKey("refent");

                    b.ToTable("entreprise", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.Marque", b =>
                {
                    b.Property<short>("codmar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("codmar");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<short>("codmar"));

                    b.Property<string>("desmar")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("desmar")
                        .UseCollation("latin1_swedish_ci");

                    b.Property<string>("lier")
                        .HasColumnType("longtext")
                        .HasColumnName("lier")
                        .UseCollation("latin1_swedish_ci");

                    b.HasKey("codmar");

                    b.ToTable("marque", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.MarqueAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Codmar")
                        .HasColumnType("smallint")
                        .HasColumnName("codmar");

                    b.Property<int>("Codvar")
                        .HasColumnType("int")
                        .HasColumnName("codvar");

                    b.Property<int>("Refver")
                        .HasColumnType("int")
                        .HasColumnName("refver");

                    b.HasKey("Id");

                    b.HasIndex("Codmar", "Refver", "Codvar")
                        .IsUnique();

                    b.ToTable("marque_assignment", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.PalBrut", b =>
                {
                    b.Property<int?>("caiver")
                        .HasColumnType("int");

                    b.Property<int?>("codsvar")
                        .HasColumnType("int");

                    b.Property<string>("codtyp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("codvar")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dterec")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("etat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("nbrcai")
                        .HasColumnType("int");

                    b.Property<int>("numpal")
                        .HasColumnType("int");

                    b.Property<int?>("numrec")
                        .HasColumnType("int");

                    b.Property<double?>("pdsfru")
                        .HasColumnType("double");

                    b.Property<int?>("refadh")
                        .HasColumnType("int");

                    b.Property<int?>("refver")
                        .HasColumnType("int");

                    b.ToTable("palbrut", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.Palette", b =>
                {
                    b.Property<int?>("codexp")
                        .HasColumnType("int");

                    b.Property<int?>("codgrp")
                        .HasColumnType("int");

                    b.Property<int?>("codmar")
                        .HasColumnType("int");

                    b.Property<string>("codtyp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("codvar")
                        .HasColumnType("int");

                    b.Property<int?>("colpal")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dtepal")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("numbdq")
                        .HasColumnType("int");

                    b.Property<int>("numpal")
                        .HasColumnType("int");

                    b.Property<decimal?>("pdscom")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("pdsfru")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable("palette", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.Palette_d", b =>
                {
                    b.Property<int?>("codvar")
                        .HasColumnType("int");

                    b.Property<int?>("nbrcol")
                        .HasColumnType("int");

                    b.Property<int?>("nbrfru")
                        .HasColumnType("int");

                    b.Property<int?>("numbdq")
                        .HasColumnType("int");

                    b.Property<int?>("numpal")
                        .HasColumnType("int");

                    b.Property<decimal?>("pdscom")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("pdsfru")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("refver")
                        .HasColumnType("int");

                    b.ToTable("palette_d", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.Reception", b =>
                {
                    b.Property<int>("Numrec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("numrec");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Numrec"));

                    b.Property<short?>("Affect")
                        .HasColumnType("smallint")
                        .HasColumnName("affect");

                    b.Property<decimal?>("Brurec")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("brurec");

                    b.Property<string>("Certif")
                        .HasColumnType("longtext")
                        .HasColumnName("certif");

                    b.Property<ushort?>("Codaff")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("codaff");

                    b.Property<string>("Codmaj")
                        .HasColumnType("longtext")
                        .HasColumnName("codmaj");

                    b.Property<int?>("Codtrj")
                        .HasColumnType("int")
                        .HasColumnName("codtrj");

                    b.Property<string>("Codtyp")
                        .HasColumnType("longtext")
                        .HasColumnName("codtyp");

                    b.Property<short?>("Codvar")
                        .HasColumnType("smallint")
                        .HasColumnName("codvar");

                    b.Property<string>("Comagri")
                        .HasColumnType("longtext")
                        .HasColumnName("comagri");

                    b.Property<string>("Coment")
                        .HasColumnType("longtext")
                        .HasColumnName("coment");

                    b.Property<DateTime?>("Dtecue")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dtecue");

                    b.Property<DateTime?>("Dterec")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dterec");

                    b.Property<DateTime?>("Dttare")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dttare");

                    b.Property<string>("Hercue")
                        .HasColumnType("longtext")
                        .HasColumnName("hercue");

                    b.Property<string>("Herrec")
                        .HasColumnType("longtext")
                        .HasColumnName("herrec");

                    b.Property<string>("Listpar")
                        .HasColumnType("longtext")
                        .HasColumnName("listpar");

                    b.Property<decimal?>("Moycai")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("moycai");

                    b.Property<double?>("Mttrans")
                        .HasColumnType("double")
                        .HasColumnName("mttrans");

                    b.Property<int?>("Nbrcai")
                        .HasColumnType("int")
                        .HasColumnName("nbrcai");

                    b.Property<int?>("Nbrcailiv")
                        .HasColumnType("int")
                        .HasColumnName("nbrcailiv");

                    b.Property<ushort?>("Nbrfru")
                        .HasColumnType("smallint unsigned")
                        .HasColumnName("nbrfru");

                    b.Property<int?>("Nbrpal")
                        .HasColumnType("int")
                        .HasColumnName("nbrpal");

                    b.Property<int?>("Nbrpalliv")
                        .HasColumnType("int")
                        .HasColumnName("nbrpalliv");

                    b.Property<decimal?>("Netrec")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("netrec");

                    b.Property<int?>("Numbl")
                        .HasColumnType("int")
                        .HasColumnName("numbl");

                    b.Property<uint?>("Numbou")
                        .HasColumnType("int unsigned")
                        .HasColumnName("numbou");

                    b.Property<int?>("Numcai")
                        .HasColumnType("int")
                        .HasColumnName("numcai");

                    b.Property<int?>("Numcaisor")
                        .HasColumnType("int")
                        .HasColumnName("numcaisor");

                    b.Property<int?>("Numord")
                        .HasColumnType("int")
                        .HasColumnName("numord");

                    b.Property<int?>("Numpes")
                        .HasColumnType("int")
                        .HasColumnName("numpes");

                    b.Property<uint?>("Numr")
                        .HasColumnType("int unsigned")
                        .HasColumnName("numr");

                    b.Property<int?>("Numtrait")
                        .HasColumnType("int")
                        .HasColumnName("numtrait");

                    b.Property<int?>("Numtrs")
                        .HasColumnType("int")
                        .HasColumnName("numtrs");

                    b.Property<string>("Numveh")
                        .HasColumnType("longtext")
                        .HasColumnName("numveh");

                    b.Property<double?>("PdsNet")
                        .HasColumnType("double")
                        .HasColumnName("pdsNet");

                    b.Property<decimal?>("Pdsech")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("pdsech");

                    b.Property<decimal?>("Pdspes")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("pdspes");

                    b.Property<string>("Pese")
                        .HasColumnType("longtext")
                        .HasColumnName("pese");

                    b.Property<short?>("Refsta")
                        .HasColumnType("smallint")
                        .HasColumnName("refsta");

                    b.Property<short?>("Refver")
                        .HasColumnType("smallint")
                        .HasColumnName("refver");

                    b.Property<decimal?>("Tarrec")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("tarrec");

                    b.Property<decimal?>("Tmprec")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("tmprec");

                    b.Property<short?>("Typcai")
                        .HasColumnType("smallint")
                        .HasColumnName("typcai");

                    b.Property<string>("Typetrns")
                        .HasColumnType("longtext")
                        .HasColumnName("typetrns");

                    b.Property<short?>("Varrec")
                        .HasColumnType("smallint")
                        .HasColumnName("varrec");

                    b.HasKey("Numrec");

                    b.ToTable("reception", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.TPalette", b =>
                {
                    b.Property<int?>("codbarq")
                        .HasColumnType("int")
                        .HasColumnName("codbarq");

                    b.Property<string>("codebar")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("codebar");

                    b.Property<int?>("codgrp")
                        .HasColumnType("int")
                        .HasColumnName("codgrp");

                    b.Property<int?>("codmar")
                        .HasColumnType("int")
                        .HasColumnName("codmar");

                    b.Property<string>("codtyp")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codtyp");

                    b.Property<short?>("codvar")
                        .HasColumnType("smallint")
                        .HasColumnName("codvar");

                    b.Property<string>("indice")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("indice");

                    b.Property<string>("lier")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("lier");

                    b.Property<string>("modtrp")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("modtrp");

                    b.Property<string>("natpal")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("natpal");

                    b.Property<int?>("nbrbar")
                        .HasColumnType("int")
                        .HasColumnName("nbrbar");

                    b.Property<int?>("nbrfil")
                        .HasColumnType("int")
                        .HasColumnName("nbrfil");

                    b.Property<string>("nomemb")
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("nomemb");

                    b.Property<decimal?>("pdcomc")
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("pdcomc");

                    b.Property<decimal?>("pdnetc")
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("pdnetc");

                    b.Property<decimal?>("pdproc")
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("pdproc");

                    b.Property<double?>("pdsbar")
                        .HasColumnType("double")
                        .HasColumnName("pdsbar");

                    b.Property<decimal?>("pdsfil")
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("pdsfil");

                    b.Property<decimal?>("prxcon")
                        .HasColumnType("decimal(16,4)")
                        .HasColumnName("prxcon");

                    b.Property<decimal?>("prxemb")
                        .HasColumnType("decimal(16,4)")
                        .HasColumnName("prxemb");

                    b.Property<decimal?>("prxpal")
                        .HasColumnType("decimal(16,4)")
                        .HasColumnName("prxpal");

                    b.Property<decimal?>("tarcol")
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("tarcol");

                    b.Property<decimal?>("tarpal")
                        .HasColumnType("decimal(16,2)")
                        .HasColumnName("tarpal");

                    b.ToTable("tpalette", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.Trait", b =>
                {
                    b.Property<int>("Ref")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ref");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Ref"));

                    b.Property<int?>("Dar")
                        .HasColumnType("int")
                        .HasColumnName("dar");

                    b.Property<double?>("Dos")
                        .HasColumnType("double")
                        .HasColumnName("dos");

                    b.Property<string>("Matieractive")
                        .HasColumnType("longtext")
                        .HasColumnName("matieractive")
                        .UseCollation("utf8mb4_unicode_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Matieractive"), "utf8mb4");

                    b.Property<string>("Nomcom")
                        .HasColumnType("longtext")
                        .HasColumnName("nomcom")
                        .UseCollation("utf8mb4_unicode_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Nomcom"), "utf8mb4");

                    b.Property<string>("Unite")
                        .HasColumnType("longtext")
                        .HasColumnName("unité")
                        .UseCollation("utf8mb4_unicode_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Unite"), "utf8mb4");

                    b.HasKey("Ref");

                    b.ToTable("trait");
                });

            modelBuilder.Entity("frutaaaaa.Models.Traitement", b =>
                {
                    b.Property<int>("Numtrait")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("numtrait");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Numtrait"));

                    b.Property<int?>("Codgrp")
                        .HasColumnType("int")
                        .HasColumnName("codgrp");

                    b.Property<int?>("Codvar")
                        .HasColumnType("int")
                        .HasColumnName("codvar");

                    b.Property<DateTime?>("Dateappli")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dateappli");

                    b.Property<DateTime?>("Dateprecolte")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dateprecolte");

                    b.Property<int?>("Ref")
                        .HasColumnType("int")
                        .HasColumnName("ref");

                    b.Property<int?>("Refver")
                        .HasColumnType("int")
                        .HasColumnName("refver");

                    b.HasKey("Numtrait");

                    b.ToTable("traitement");
                });

            modelBuilder.Entity("frutaaaaa.Models.TypeEcart", b =>
                {
                    b.Property<int>("codtype")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("codtype"));

                    b.Property<string>("destype")
                        .HasColumnType("longtext");

                    b.Property<string>("lier")
                        .HasColumnType("longtext");

                    b.HasKey("codtype");

                    b.ToTable("typeecart", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("frutaaaaa.Models.Variete", b =>
                {
                    b.Property<int>("codgrv")
                        .HasColumnType("int");

                    b.Property<int>("codvar")
                        .HasColumnType("int");

                    b.Property<string>("nomvar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("variete", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.Vente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE")
                        .HasColumnName("date_vente");

                    b.Property<double>("MontantTotal")
                        .HasColumnType("DOUBLE")
                        .HasColumnName("montant_total");

                    b.Property<int?>("Numbonvente")
                        .HasColumnType("int");

                    b.Property<int?>("Numlot")
                        .HasColumnType("int")
                        .HasColumnName("numlot");

                    b.Property<double>("PoidsTotal")
                        .HasColumnType("DOUBLE")
                        .HasColumnName("poids_total");

                    b.Property<double>("Price")
                        .HasColumnType("DOUBLE");

                    b.HasKey("Id");

                    b.ToTable("vente", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.Verger", b =>
                {
                    b.Property<string>("nomver")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("refadh")
                        .HasColumnType("int");

                    b.Property<int>("refver")
                        .HasColumnType("int");

                    b.ToTable("verger", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.ViewExpVerVar", b =>
                {
                    b.Property<int>("coddes")
                        .HasColumnType("int");

                    b.Property<int>("codvar")
                        .HasColumnType("int");

                    b.Property<decimal>("pdscom")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("SUM(p.pdscom)");

                    b.Property<int>("refver")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("view_expvervar", (string)null);
                });

            modelBuilder.Entity("DailyProgramDetail", b =>
                {
                    b.HasOne("frutaaaaa.Models.DailyProgram", null)
                        .WithMany("Details")
                        .HasForeignKey("DailyProgramId");
                });

            modelBuilder.Entity("UserPagePermission", b =>
                {
                    b.HasOne("frutaaaaa.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("frutaaaaa.Models.EcartDirect", b =>
                {
                    b.HasOne("frutaaaaa.Models.TypeEcart", "TypeEcart")
                        .WithMany()
                        .HasForeignKey("Codtype")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TypeEcart");
                });

            modelBuilder.Entity("frutaaaaa.Models.DailyProgram", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
