// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using frutaaaaa.Data;

#nullable disable

namespace frutaaaaa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250723121224_AddEcartTable")]
    partial class AddEcartTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DailyProgramDetail", b =>
                {
                    b.Property<int>("NumProg")
                        .HasColumnType("int");

                    b.Property<int>("codgrv")
                        .HasColumnType("int");

                    b.Property<int?>("DailyProgramId")
                        .HasColumnType("int");

                    b.Property<int>("Nbrcoli")
                        .HasColumnType("int");

                    b.Property<int>("Nbrpal")
                        .HasColumnType("int");

                    b.Property<int>("Valide")
                        .HasColumnType("int");

                    b.Property<string>("codtyp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NumProg", "codgrv");

                    b.HasIndex("DailyProgramId");

                    b.ToTable("DailyProgramDetails");
                });

            modelBuilder.Entity("Destination", b =>
                {
                    b.Property<int>("coddes")
                        .HasColumnType("int");

                    b.Property<string>("vildes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("destination", (string)null);
                });

            modelBuilder.Entity("GrpVar", b =>
                {
                    b.Property<int>("codgrv")
                        .HasColumnType("int");

                    b.Property<string>("nomgrv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("grpvar", (string)null);
                });

            modelBuilder.Entity("Partenaire", b =>
                {
                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ref")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("partenaire", (string)null);
                });

            modelBuilder.Entity("TPalette", b =>
                {
                    b.Property<string>("codtyp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nomemb")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("tpalette", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.DailyProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Coddes")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dteprog")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Havday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumProg")
                        .HasColumnType("int");

                    b.Property<string>("PO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Refexp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyPrograms");
                });

            modelBuilder.Entity("frutaaaaa.Models.EcartE", b =>
                {
                    b.Property<int>("codtype")
                        .HasColumnType("int");

                    b.Property<int>("codvar")
                        .HasColumnType("int");

                    b.Property<DateTime>("dtepal")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("numpal")
                        .HasColumnType("int");

                    b.Property<double>("pdsfru")
                        .HasColumnType("double");

                    b.Property<double>("pdspes")
                        .HasColumnType("double");

                    b.Property<int?>("refver")
                        .HasColumnType("int");

                    b.Property<double>("tarpal")
                        .HasColumnType("double");

                    b.ToTable("ecart_e", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.PalBrut", b =>
                {
                    b.Property<int?>("caiver")
                        .HasColumnType("int");

                    b.Property<int?>("codsvar")
                        .HasColumnType("int");

                    b.Property<string>("codtyp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("codvar")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dterec")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("etat")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("nbrcai")
                        .HasColumnType("int");

                    b.Property<int>("numpal")
                        .HasColumnType("int");

                    b.Property<int?>("numrec")
                        .HasColumnType("int");

                    b.Property<double?>("pdsfru")
                        .HasColumnType("double");

                    b.Property<int?>("refadh")
                        .HasColumnType("int");

                    b.Property<int?>("refver")
                        .HasColumnType("int");

                    b.ToTable("palbrut", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.Palette", b =>
                {
                    b.Property<int?>("codexp")
                        .HasColumnType("int");

                    b.Property<int?>("codgrp")
                        .HasColumnType("int");

                    b.Property<int?>("codmar")
                        .HasColumnType("int");

                    b.Property<string>("codtyp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("codvar")
                        .HasColumnType("int");

                    b.Property<int?>("colpal")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dtepal")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("numbdq")
                        .HasColumnType("int");

                    b.Property<int>("numpal")
                        .HasColumnType("int");

                    b.Property<decimal?>("pdscom")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("pdsfru")
                        .HasColumnType("decimal(65,30)");

                    b.ToTable("palette", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.Palette_d", b =>
                {
                    b.Property<int?>("codvar")
                        .HasColumnType("int");

                    b.Property<int?>("nbrcol")
                        .HasColumnType("int");

                    b.Property<int?>("nbrfru")
                        .HasColumnType("int");

                    b.Property<int?>("numbdq")
                        .HasColumnType("int");

                    b.Property<int?>("numpal")
                        .HasColumnType("int");

                    b.Property<decimal?>("pdscom")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("pdsfru")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("refver")
                        .HasColumnType("int");

                    b.ToTable("palette_d", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("frutaaaaa.Models.Variete", b =>
                {
                    b.Property<int>("codvar")
                        .HasColumnType("int");

                    b.Property<string>("nomvar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.ToTable("variete", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.Verger", b =>
                {
                    b.Property<string>("nomver")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("refadh")
                        .HasColumnType("int");

                    b.Property<int>("refver")
                        .HasColumnType("int");

                    b.ToTable("verger", (string)null);
                });

            modelBuilder.Entity("DailyProgramDetail", b =>
                {
                    b.HasOne("frutaaaaa.Models.DailyProgram", null)
                        .WithMany("Details")
                        .HasForeignKey("DailyProgramId");
                });

            modelBuilder.Entity("frutaaaaa.Models.DailyProgram", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
