// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using frutaaaaa.Data;

#nullable disable

namespace frutaaaaa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DailyProgramDetail", b =>
                {
                    b.Property<int>("NumProg")
                        .HasColumnType("int");

                    b.Property<int>("codgrv")
                        .HasColumnType("int");

                    b.Property<int?>("DailyProgramId")
                        .HasColumnType("int");

                    b.Property<int>("Nbrcoli")
                        .HasColumnType("int");

                    b.Property<int>("Nbrpal")
                        .HasColumnType("int");

                    b.Property<int>("Valide")
                        .HasColumnType("int");

                    b.Property<string>("codtyp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NumProg", "codgrv");

                    b.HasIndex("DailyProgramId");

                    b.ToTable("DailyProgramDetails");
                });

            modelBuilder.Entity("Destination", b =>
                {
                    b.Property<int>("coddes")
                        .HasColumnType("int")
                        .HasColumnName("coddes");

                    b.Property<string>("vildes")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("vildes");

                    b.ToTable("destination", (string)null);
                });

            modelBuilder.Entity("Partenaire", b =>
                {
                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nom");

                    b.Property<int>("ref")
                        .HasColumnType("int")
                        .HasColumnName("ref");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.ToTable("partenaire", (string)null);
                });

            modelBuilder.Entity("TPalette", b =>
                {
                    b.Property<string>("codtyp")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("codtyp");

                    b.Property<string>("nomemb")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nomemb");

                    b.ToTable("tpalette", (string)null);
                });

            modelBuilder.Entity("frutaaaaa.Models.DailyProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Coddes")
                        .HasColumnType("int");

                    b.Property<DateTime>("Dteprog")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Havday")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Lot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumProg")
                        .HasColumnType("int");

                    b.Property<string>("PO")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Refexp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyPrograms");
                });

            modelBuilder.Entity("frutaaaaa.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("grpvar", b =>
                {
                    b.Property<int>("codgrv")
                        .HasColumnType("int")
                        .HasColumnName("codgrv");

                    b.Property<string>("nomgrv")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nomgrv");

                    b.ToTable("grpvar", (string)null);
                });

            modelBuilder.Entity("DailyProgramDetail", b =>
                {
                    b.HasOne("frutaaaaa.Models.DailyProgram", null)
                        .WithMany("Details")
                        .HasForeignKey("DailyProgramId");
                });

            modelBuilder.Entity("frutaaaaa.Models.DailyProgram", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
